baseURL = 'https://lemric.com/'
languageCode = 'pl-pl'
title = 'Lemric'
theme = 'hermit'
[author]
  name = "Lemric Dominik Labudzinski NIP: 5272448444"
[params]
  AuthorName = 'Lemric Dominik Labudzinski NIP: 5272448444'
  GitHubUser = 'alembic'
  SidebarRecentLimit = 5
  homeSubtitle = ''
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
[[params.social]]
      name      = "github"
      icon_pack = "fab"
      url       = "https://github.com/labudzinski"
[[params.social]]
      name      = "linkedin"
      icon_pack = "fab"
      url       = "https://www.linkedin.com/in/dominik-l/"
[[params.social]]
      name      = "github"
      icon_pack = "fab"
      url       = "https://github.com/lemric"
